### ISSUE TITLE
Integration compatibility: nuked mongo

### ISSUE THREAD

**Issue by janat08** [TelescopeJS/Telescope#1401]
Just copied and pasted all of the packages listings into packages file.
```
C:\Users\ALERATOR\garlic>meteor npm install
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[   ...............] - cloneCurrentTree: sill cloneCurrentTree Finishing
[        ..........] / loadDevDeps: sill install loadAllDepsIntoIdealTree
[          ........] \ diffTrees: sill install generateActionsToTake


C:\Users\ALERATOR\garlic>meteor
[[[[[ C:\Users\ALERATOR\garlic ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading package meteorhacks:kadira-binary-deps@1.4.0:
   error: Command failed: gyp
   npm ERR! Windows_NT 10.0.10586
   npm ERR! argv
   "C:\\Users\\ALERATOR\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4_4\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe"
   "C:\\Users\\ALERATOR\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4_4\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "rebuild"
   npm ERR! node v0.10.46
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! usage@0.5.0 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the usage@0.5.0 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm
   installed.
   npm ERR! If you do, this is most likely a problem with the usage
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this
   project with:
   npm ERR!     npm bugs usage
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls usage
   npm ERR! There is likely additional logging output above.

   gyp
   npm ERR! Windows_NT 10.0.10586
   npm ERR! argv
   "C:\\Users\\ALERATOR\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4_4\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe"
   "C:\\Users\\ALERATOR\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4_4\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "rebuild"
   npm ERR! node v0.10.46
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! usage@0.5.0 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the usage@0.5.0 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm
   installed.
   npm ERR! If you do, this is most likely a problem with the usage
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this
   project with:
   npm ERR!     npm bugs usage
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls usage
   npm ERR! There is likely additional logging output above.

=> Your application has errors. Waiting for file change.
```

**Comment by SachaG** [comment]
You can remove `nova:kadira` if you don't need it, it's optional.

**Comment by janat08** [comment]
Thanks for quick fix.

**Comment by janat08** [comment]
I suppose I should also copy the package.json file now?

**Comment by SachaG** [comment]
Any reason why you're not just following the install instructions in the documentation?

**Comment by janat08** [comment]
I felt like it's something I'd avoid if installing on top of existing project. There used to be a separate repo for doing that. Will push and clone telescope.

**Comment by SachaG** [comment]
I guess if the existing project is also a Telescope project then yeah, that's a good approach. 

BTW the reason I deprecated the other sample-project repo is that most people wanted to have access to the core code for reference purpose anyway.

**Comment by janat08** [comment]
Didn't want to deal with authentication for cloning the app, so I copied and pasted diligently, works out well. modifying const AppRoutes to path '/forums' is not as much a simple matter. Are there guides to working things out, as in simply logging in will result in conflicts where layout from original app will come through, and I'm in between flowrouter and vue router.

**Comment by janat08** [comment]
W20160719-02:22:16.072(6)? (STDERR) WARNING: npm peer requirements (for reactrouter:react-router-ssr) not installed:
W20160719-02:22:16.301(6)? (STDERR)  - react-router@3.0.0-alpha.1 installed, react-router@2.x needed
W20160719-02:22:16.304(6)? (STDERR)
W20160719-02:22:16.306(6)? (STDERR) Read more about installing npm peer dependencies:
W20160719-02:22:16.309(6)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies

**Comment by janat08** [comment]
Did meteor reset, and there're still conflicts: after visiting telescope path, it will remain in view after exiting path. Editing path doesn't appear to serve as a prefix, "/forums" omitted.

**Comment by janat08** [comment]
react router 3 alpha is specified in project repo.

**Comment by janat08** [comment]
and then collections by aldeed appears to desire schema for users :P

**Comment by janat08** [comment]
In addition it obliterated my mongo, after both reset and deletion of local files none of my other declarations will come through after having branched of deleting everything telescope related. Dr Mongo will only show this collections:
 meteor_accounts_loginServiceConfiguration
2. meteor_oauth_pendingCredentials
3. roles
4. users

**Comment by janat08** [comment]
is there another issue topic about compatibility of telescope with another application?

**Comment by SachaG** [comment]
Well, Telescope was never made to work with another application. Not saying it can't be done, but it's definitely not the intended use case.

**Comment by janat08** [comment]
Youre halfway there with packages. How do I unscrew my collections?

**Comment by SachaG** [comment]
You could remove the `nova:users` package and then provide your own version of the `Users` class?

**Comment by janat08** [comment]
None of the packages are actually installed.

**Comment by janat08** [comment]
Rolling back to previous commits doesn't help either.

**Comment by SachaG** [comment]
Sorry it's really hard to help since I don't know what app you're trying to integrate Nova with. To be honest I would probably recommend against what you're trying to do, but it'd be interesting if you do get it to work.

**Comment by janat08** [comment]
Right now I'm content with just getting my MongoDB unscrewed.

**Comment by SachaG** [comment]
How is it screwed? You can always do `meteor reset`.

**Comment by janat08** [comment]
It only holds collections mentioned from before, without a trace of collections from original app. I've done everything to try and scrap and restart mongo with collections declared in my app.

**Comment by capensisma** [comment]
You should have been using a dedicated mongodb database instead of a local one so you can have backups!

also this comes with no warranty use with your own risk!

**Comment by janat08** [comment]
Ill try and reinstall mongo and/or meteor.

**Comment by SachaG** [comment]
If you A) remove all Nova packages and code from your app and B) run `meteor reset` then I don't really see any way that Nova could still affect your app. Any problems would then be unrelated to it.

**Comment by janat08** [comment]
Running various commits results in same bug

**Comment by janat08** [comment]
I tried running import main.js on some file and that required meteor reset after I corrected mistake

**Comment by SachaG** [comment]
Honestly this whole thread is extremely confusing and seems more about general Meteor issues than anything related to Nova. I'm closing it for now, if you run into any Nova-specific issues feel free to open other threads.

**Comment by janat08** [comment]
Is there even a roles collection in telescope app, if yes than I'll continue trying to cleanse this machine with reinstall of meteor.

**Comment by SachaG** [comment]
I still can't understand anything about your situation, sorry. Why would it matter whether there's a roles collection, and what does that have to do with reinstalling Meteor??

**Comment by janat08** [comment]
I have nothing other than superstition to go on.

**Comment by janat08** [comment]
I roll back/reset/revert my app on local machine to a very early version of the app and it still will only have collections from recent one.
