### ISSUE TITLE
Setup Telescope on Windows

### ISSUE THREAD

**Issue by atherdon** [TelescopeJS/Telescope#1574]
Hi there, thank you for your work!

Just trying to launch Telescope on Windows 10 and got some issues. Hope this can save some time to other githubers!

1) **bcrypt fails at the install script at node-gyp rebuild**
I get this errors when trying to run npm install with "bcrypt"  as a dependency

`error bcrypt@0.8.7 install: node-gyp rebuild`
`error Exit status 1`
`error Failed at the bcrypt@0.8.7 install script.`
`error This is most likely a problem with the bcrypt package,`
`error not with npm itself.`
`error Tell the author that this fails on your system:`
`error     node-gyp rebuild`
`error You can get their info via:`
`error     npm owner ls bcrypt`
`error There is likely additional logging output above.`
`error System Windows_NT 10.0.10586`

Solution: Based on [https://github.com/kelektiv/node.bcrypt.js/issues/432#issuecomment-230595650](url) 
I'm using bcrypt-nodejs module. You need to run this line in command line:
`npm install --save bcrypt-nodejs && npm uninstall --save bcrypt`

2) **prestart_nova.sh fails after npm start**
Then I get this message when i try to run project:
`npm ERR! Failed at the Nova@1.1.0 prestart script 'sh prestart_nova.sh". `
`'sh' is not recognized as an internal or external command,
operable program or batch file.`

Solution for me:

- delete "prestart" option from package.json file

- rename sample_settings.json to settings.json

- run npm start

**Comment by meteorplus** [comment]
This issue is already solved by Microsoft

http://vujade.co/nodejs-environment-setup-with-bcrypt-module/

**Comment by atherdon** [comment]
@meteorplus I don't think that your solution is more easy than mine. But thanks for sharing! I hope this information will save some time to other diggers

**Comment by meteorplus** [comment]
well my solution you just install that software and it works!

**Comment by xavcz** [comment]
Updated on `devel` to have the colors recognition in the script. This doesn't solve completely this issue however.

Would you mind doing a PR somewhere in the docs (nova-docs.telescopeapp.org) to refer windows usage?

**Comment by atherdon** [comment]
@xavcz Ok, I can contribute to docs section about usage on Windows. Maybe later I'll find out somethings else...

**Comment by xavcz** [comment]
Sweet!
