### ISSUE TITLE
Issue for non-admin users

### ISSUE THREAD

**Issue by awrelll** [TelescopeJS/Telescope#834]
When users try to edit their own post they get this error  "get the error message Disallowed property detected: categories.0."

From the JS console:

//Disallowed property detected: categories.0
0e99b08212fd4d624ea0bf9a089bd85ed70899b0.js:3
Exception while simulating the effect of invoking 'editPost'

**Comment by yourcelf** [comment]
It looks like this is related to https://github.com/aldeed/meteor-autoform/issues/765.  AutoForm is now creating modifier docs like

    {$set: {"categories.0": "id1", "categories.1": "id2"}}

instead of

    {$set: {"categories": ["id1", "id2"]}}

This impacts both the permissions check for updating categories and the value that gets set if categories is null (mongo will interpret the set as creating an object if there isn't a "categories" array present).

I'm working on a fix for both right now.

**Comment by SachaG** [comment]
Oh you're right. I forgot about this issue as well (see also https://github.com/TelescopeJS/Telescope/issues/828)

**Comment by awrelll** [comment]
Any available fix so far ? Thanks!

**Comment by SachaG** [comment]
This should be fixed on the `devel` branch.

**Comment by awrelll** [comment]
Cant you please point me to the fix ? I updated to aldeed:autoform  5.1.0 and still got the issue.
Thanks!

**Comment by SachaG** [comment]
If you're running the latest AutoForm, then saving a form should overwrite categories with a new array. Is that not the case?

**Comment by awrelll** [comment]
Yes. But i still get the error 
"//Disallowed property detected: categories.0"

**Comment by SachaG** [comment]
That's strange. Does that happen on new posts as well?

**Comment by awrelll** [comment]
no, just non-admins when trying to edit their own post. here's the repo https://github.com/ethereumbuilders/eth.hangouts
Thanks for your reply!

**Comment by awrelll** [comment]
can i get some hint for my issue ? i can't figure it out. please!
Thank you !

**Comment by SachaG** [comment]
I tried running the repo but I ran into a couple errors:

```
=> Errors prevented startup:

   While building package cb-theme:
   error: File not found: lib/client/stylesheets/plexus.css

   While building package cb-theme-pages:
   error: File not found: lib/client/templates/plexus.html
   error: File not found: lib/client/templates/plexus.js
   error: File not found: lib/client/templates/plexus_link.html
```

But I wonder if this couldn't just be a problem affecting older posts which have been stored using the incorrect, non-array format? If a user creates a new post and tries to edit it, they also get this issue?

**Comment by awrelll** [comment]
yeah, new posts are also afected.

**Comment by SachaG** [comment]
If you can fix the repo errors I'll take another look.

**Comment by awrelll** [comment]
i added the files to the repo. it should be ok now. thanks!
